version: '3.9'
services:
  redis:
    image: redis:7
    container_name: email_redis
    ports:
      - "6379:6379"
  backend:
    build: ./backend
    container_name: email_backend
    env_file: ./backend/.env
    depends_on:
      - redis
    ports:
      - "8080:8000"
volumes:
  pgdata:
